# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerstatus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='secondname',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='date',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
