# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 23:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tuerstatus', '0002_auto_20151215_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='date',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 14, 23, 52, 9, 233619, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
