# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerstatus', '0003_auto_20151215_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
