# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerstatus', '0005_date_repeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
