# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuerstatus', '0006_auto_20160126_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='link',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='date',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
